# Generated by Django 4.2.1 on 2023-07-24 22:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('product_name', models.CharField(help_text='Name of product', max_length=64)),
                ('count', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Buy',
                'verbose_name_plural': 'Buys',
                'ordering': ('-date', 'product_name', 'count'),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a category (e.g. Oil, Tire etc.)', max_length=64, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('phone', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Producer',
                'verbose_name_plural': 'Producers',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('phone', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Provider',
                'verbose_name_plural': 'Providers',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('name', models.CharField(max_length=64)),
                ('article', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this product', primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.category')),
                ('producer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.producer')),
                ('providers', models.ManyToManyField(help_text='Select a provider for this product', to='shop.provider')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('name',),
            },
        ),
    ]
