# Generated by Django 4.2.1 on 2023-07-24 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
