# Generated by Django 4.2.1 on 2023-07-25 21:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_producer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='address',
            field=models.CharField(max_length=64, validators=[django.core.validators.RegexValidator('\\+375\\s*\\(\\s*29\\s*\\)\\s*\\d{3}\\s*-\\s*\\d{2}\\s*-\\s*\\d{2}', 'phone number is incorrect.', code='invalid')]),
        ),
    ]
