# Generated by Django 4.2.1 on 2023-07-25 23:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_alter_producer_phone_alter_provider_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='count',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Count must be positive.')]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Price must be not negative.')]),
        ),
    ]
