# Generated by Django 4.2.1 on 2023-08-05 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_profile_av_alter_producer_phone_alter_profile_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='av',
        ),
    ]
