# Generated by Django 4.2.1 on 2023-08-08 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_alter_product_options_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'permissions': [('provide_product', 'Can provide Product')], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
