# Generated by Django 4.2.1 on 2023-08-08 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_remove_product_providers_product_providers_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='providers_1',
            new_name='providers',
        ),
    ]
