# Generated by Django 4.2.1 on 2023-08-08 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_rename_providers_1_product_providers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'permissions': [('provide_product', 'Can provide Products')], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
