# Generated by Django 4.2.1 on 2023-08-09 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_delete_provider_remove_product_producer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='providers1',
            new_name='providers',
        ),
    ]
