# Generated by Django 4.2.1 on 2023-08-09 20:18

from django.conf import settings
from django.db import migrations
import apps.core.model_tools
import apps.shop.validators
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0026_rename_providers1_product_providers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='providers',
            field=models.ManyToManyField(blank=True, help_text='Select a provider for this product', to=settings.AUTH_USER_MODEL, validators=[apps.shop.validators.validate_provider]),
        ),
    ]
