# Generated by Django 4.2.1 on 2023-08-10 19:31

from django.conf import settings
from django.db import migrations
from django.db import models
import apps.shop.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0027_alter_product_providers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='providers',
            field=models.ManyToManyField(blank=True, help_text='Select a provider for this product', related_name='products', to=settings.AUTH_USER_MODEL, validators=[apps.shop.validators.validate_provider]),
        ),
    ]
