# Generated by Django 4.2.1 on 2023-08-13 13:39

from django.db import migrations, models
import apps.core.media_tools


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_alter_product_providers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='profile_avatars/avatar_default.jpg', null=True, storage=apps.core.media_tools.OverwriteStorage(), upload_to='profile_avatars'),
        ),
    ]
