# Generated by Django 4.2.1 on 2023-08-16 11:00

import apps.shop.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0031_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='providers',
            field=models.ManyToManyField(blank=True, help_text='Select a provider for this product', related_name='products', to=settings.AUTH_USER_MODEL, validators=[apps.shop.validators.validate_provider]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=64, validators=[apps.shop.validators.FullMatchRegexValidator('((\\b([A-Za-z]+)\\b)|(\\b([\\d\\.\\-]+)\\b)|([\\s,\\.\\:\\!]*))*', 'Address is incorrect. It must consist of words, numbers and codes.', code='invalid')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=apps.core.model_tools.AvatarField(blank=True, default='profile_avatars/avatar_default.jpg', storage=apps.core.media_tools.OverwriteCodedStorage(), upload_to='profile_avatars'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(help_text='Enter a phone in format +375 (29) XXX-XX-XX', max_length=64, validators=[apps.shop.validators.FullMatchRegexValidator('\\+375\\s*\\(\\s*29\\s*\\)\\s*(\\d{3})\\s*-\\s*(\\d{2})\\s*-\\s*(\\d{2})', 'Phone number is incorrect. Correct format is +375 (29) XXX-XX-XX.', code='invalid')]),
        ),
    ]
