# Generated by Django 4.2.1 on 2023-08-24 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0032_alter_product_providers_alter_profile_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
