# Generated by Django 4.2.1 on 2023-08-24 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buy',
            options={'ordering': ('-date', 'product_name', 'count'), 'verbose_name': 'buy', 'verbose_name_plural': 'buys'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'permissions': [('provide_product', 'Can provide Products')], 'verbose_name': 'product', 'verbose_name_plural': 'products'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'profile', 'verbose_name_plural': 'profiles'},
        ),
    ]
