# Generated by Django 4.2.1 on 2023-09-05 21:58

import apps.core.media_tools.storages
import apps.core.model_tools.avatar_field
import apps.core.model_tools.named_image_field
import apps.core.model_tools.svg_field
import apps.shop.model_funcs
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0036_delete_provider_provider_alter_product_providers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=apps.core.model_tools.named_image_field.NamedImageField(default='categories_images/image_default.png', get_filename=apps.shop.model_funcs.get_category_image_filename, storage=apps.core.media_tools.storages.OverwriteCodedStorage(), upload_to='categories_images'),
        ),
        migrations.AddField(
            model_name='category',
            name='logo',
            field=apps.core.model_tools.svg_field.SvgField(default='categories_logo/logo_default.svg', get_filename=apps.shop.model_funcs.get_category_logo_filename, storage=apps.core.media_tools.storages.OverwriteCodedStorage(), upload_to='categories_logo', validators=[apps.core.model_tools.svg_field.validate_svg]),
        ),
        migrations.AddField(
            model_name='category',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique ID for this product', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=apps.core.model_tools.avatar_field.AvatarField(avatar_size=300, blank=True, default='profile_avatars/avatar_default.jpg', get_color=apps.shop.model_funcs.get_profile_avatar_color, get_filename=apps.shop.model_funcs.get_profile_avatar_filename, storage=apps.core.media_tools.storages.OverwriteCodedStorage(), upload_to='profile_avatars'),
        ),
    ]
