# Generated by Django 4.2.1 on 2023-09-10 11:02

import apps.core.media_tools.storages
import apps.core.model_tools.named_image_field
import apps.shop.model_funcs
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0037_alter_provider_options_category_image_category_logo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('image', apps.core.model_tools.named_image_field.NamedImageField(get_filename=apps.shop.model_funcs.get_carousel_item_image_filename, storage=apps.core.media_tools.storages.OverwriteCodedStorage(), upload_to='carousel_items_images')),
                ('title', models.CharField(max_length=64)),
                ('subtitle', models.CharField(max_length=64)),
            ],
        ),
    ]
