# Generated by Django 4.2.1 on 2023-09-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0038_carouselitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carouselitem',
            name='subtitle',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='carouselitem',
            name='title',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
