# Generated by Django 4.2.1 on 2023-09-10 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0039_alter_carouselitem_subtitle_alter_carouselitem_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buy',
            options={'ordering': ('-date', 'product', 'count'), 'verbose_name': 'buy', 'verbose_name_plural': 'buys'},
        ),
        migrations.RemoveField(
            model_name='buy',
            name='product_name',
        ),
        migrations.AddField(
            model_name='buy',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product'),
        ),
        migrations.AddField(
            model_name='buy',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
