# Generated by Django 4.2.1 on 2023-09-10 20:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0040_alter_buy_options_remove_buy_product_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy',
            name='card_num',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(limit_value=0, message='Card number must be not negative.')]),
        ),
    ]
