# Generated by Django 4.2.1 on 2023-09-10 20:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_buy_card_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='card_num',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=0, message='Card number must be not negative.')]),
        ),
    ]
