# Generated by Django 4.2.1 on 2023-09-10 20:17

import apps.core.media_tools.storages
import apps.core.model_tools.named_image_field
import apps.shop.model_funcs
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_alter_buy_card_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=apps.core.model_tools.named_image_field.NamedImageField(blank=True, get_filename=apps.shop.model_funcs.get_product_image_filename, storage=apps.core.media_tools.storages.OverwriteCodedStorage(), upload_to='products_images'),
        ),
        migrations.AddField(
            model_name='product',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
