# Generated by Django 4.2.1 on 2023-09-10 20:33

import apps.core.media_tools.storages
import apps.core.model_tools.named_image_field
import apps.shop.model_funcs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_product_image_product_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=apps.core.model_tools.named_image_field.NamedImageField(get_filename=apps.shop.model_funcs.get_product_image_filename, storage=apps.core.media_tools.storages.OverwriteCodedStorage(), upload_to='products_images'),
        ),
    ]
