# Generated by Django 4.2.1 on 2023-09-11 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0050_coupon_profile_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='coupon',
        ),
        migrations.AddField(
            model_name='faq',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
