# Generated by Django 4.2.1 on 2023-09-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0054_alter_buy_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='coupons',
            field=models.ManyToManyField(blank=True, help_text='Select a coupon for this user', related_name='users', to='shop.coupon'),
        ),
    ]
