# Generated by Django 4.2.1 on 2023-09-22 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0057_alter_buy_product_alter_buy_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buy',
            options={'ordering': ('-date', 'product', 'user', 'count'), 'verbose_name': 'buy', 'verbose_name_plural': 'buys'},
        ),
    ]
