# Generated by Django 4.2.1 on 2023-09-22 17:57

import apps.core.model_tools.integer_range_field
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0059_alter_review_options_alter_coupon_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='discount',
            field=apps.core.model_tools.integer_range_field.IntegerRangeField(max_value=100, min_value=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
