# Generated by Django 4.2.1 on 2023-09-22 18:01

import apps.core.model_tools.integer_range_field
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0060_alter_buy_count_alter_coupon_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='card_num',
            field=apps.core.model_tools.integer_range_field.IntegerRangeField(max_value=1000000, min_value=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='buy',
            name='count',
            field=apps.core.model_tools.integer_range_field.IntegerRangeField(max_value=None, min_value=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
